name: Compile LaTeX Resume to README
permissions: write-all
on:
  push:
    paths:
      - resume.tex
jobs:
  convert-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persistent-credentials: true

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base

      - name: Convert resume.tex to README.md
        run: |
          pandoc resume.tex -o README.md --from=latex --to=gfm --wrap=preserve

      - name: Upload README.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README.md from resume.tex" || echo "No changes to commit"
          git pull --rebase origin main
          git push || echo "Push failed. Re-run workflow if necessary."
