name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Compile LaTeX document 
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
