name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persistent-credentials: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Upload PDF file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add resume.pdf
          git commit -m "Update PDF file" || echo "No changes to commit"
          git push
